replicating linter from Cloud AI notebooks

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,25 +1,32 @@
 name: ci
-on:
-  pull_request:
-    branches:
-      - main
+on: pull_request
 
 jobs:
-  run-linters:
+  format_and_lint:
     name: notebook format and lint
     runs-on: ubuntu-latest
-
     steps:
     - name: Set up Python
       uses: actions/setup-python@v2
     - name: Fetch pull request branch
       uses: actions/checkout@v2
-    - name: Fetch base master branch
+    - name: Fetch base main branch
       run: git fetch -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" main:main
     - name: Install requirements
       run: python3 -m pip install -U -r .github/workflows/linter/requirements.txt
-    - name: Run linters
-      uses: wearerequired/lint-action@v1
-      with:
-        black: true
-        flake8: true
+    - name: Format and lint notebooks
+      run: |
+        set +e
+        .github/workflows/linter/run_linter.sh -t
+        RTN=$?
+        if [ "$RTN" != "0" ]; then
+          echo "There were problems formatting/linting the notebooks."
+          echo "Please run the following commands locally from the root directory to attempt to autofix the issues:"
+          echo ""
+          echo "python3 -m pip install -U -r .github/workflows/linter/requirements.txt"
+          echo ".github/workflows/linter/run_linter.sh"
+          echo ""
+          echo "If it can't be autofixed, please fix them manually."
+          echo "Then, commit the fixes and push again."
+          exit 1
+        fi
